---
title: "PLAT4TERFOOD"
format: pdf
editor: visual
---
## Packages

```{r}
library(readxl)
library(dplyr)
library(tidyverse)
library(kableExtra)
```

## Imporation des données

```{r}

data <- read_excel("24407_Export.xlsx")

```

## Questions :

### 1.Pour chaque lieu. Expression des fréquences des courses (Q6)

```{r}
  
fc <- data %>%
  select(Q6_1:Q6_12) %>%
  pivot_longer(
    cols = Q6_1:Q6_12,
    names_to = "Q6",
    values_to = "value")

# On transforme avec les bon nom poiur une meilleur lisibilité

fc$Q6 <- factor(fc$Q6, levels = paste("Q6_", seq(1:12), sep = ""), labels = c("Hypermarché, Supermarché","Hard discount","Epiceries indépendantes, de quartier, épiceries fines","Magasins de surgelés","Magasins spécialisés Bio","Marché","Directement aux agriculteurs","Paniers en ligne réalisés par un intermédiaire","Artisans et commerçants spécialisés","Epicerie participative, associative, supermarché coopératif","Magasin alimentaire spécialisé dans le vrac ou les produits locaux","Magasin d’aide alimentaire"))

fc$value <- factor(fc$value, levels = 1:7, labels = c("Plusieurs fois par semaine","1 fois par semaine","2 à 3 fois par mois","1 fois par mois","Moins d’une fois par mois","Seulement pour des événements particuliers","Jamais"))


fc_prop <- round(prop.table(table(fc$Q6, fc$value),1)*100, 2)

kable(fc_prop, captation = "Taux de réquentation en fonction des lieux d'achat" ) %>% # mise en forme du tableau
  kable_styling(latex_options = "striped") %>%
  footnote(general = "Format des données en pourcentage" )
```

### 2.Nombre de lieux fréquentés très régulièrement (réponses 1/2) en moyenne

```{r}
dt_nb_moy <- data %>% # selection des bonnes colonnes
  select(Q6_1:Q6_12)

nb_tres_freq <- rowSums(dt_nb_moy == 1 | dt_nb_moy == 2) # On compte le nombre de lieu très fréquenté par individu

print(paste("Les répondants fréquentent en moyenne ",round(mean(nb_tres_freq),1)," lieux très régulièrement (au moins une fois par semaine)"))
```



