---
title: "Renommage_ variables"
format: html
editor: visual
---

# Import des librairies 

```{r,message=FALSE}
library(readxl) # Importer le fichier Excel
library(dplyr)
```

# Chargement du jeu de données 

```{r}
data <- read_excel("24407_Export.xlsx")
```

# Questions 1 à 6

## Renommage des variables 

```{r}
data <- data |> 
  rename(
    "Identifiant" = "Num",
    "Sexe" = "Q1" ,
    "Age" = "Q2",
    "Tranche d'âge" ="recode_age",
    "CSP" = "Q3", 
    "Groupe de CSP" ="recode_csp", 
    "Responsable achats alimentaire"="Q4", 
    "Code postal"="Q5",
    "Ville"="Q5_ville",
    "Nombre habitants"="Q5_taille",
    "Code officiel géographique de la Commune "="Q5_insee",
    "Département"="Q5_departement",
    "Hypermarché, Supermarché"="Q6_1",
    "Hard discount"="Q6_2",
    "Epiceries indépendantes, de quartier, épiceries fines"="Q6_3",
    "Magains de surgelés"="Q6_4",
    "Magasins spécialisés Bio"="Q6_5",         
    "Marché" ="Q6_6",
    "Directement aux agriculteurs"="Q6_7",
    "Paniers en ligne réalisés par un intermédiaire"="Q6_8",
    "Artisans et commerçants spécialisés"="Q6_9",
    "Epicerie participative, associative, supermarché coopératif"="Q6_10",
    "Magasin alimentaire spécialisé dans le vrac ou les produits locaux"="Q6_11",
    "Magasin d’aide alimentaire"="Q6_12",       
    "Autre"="Q6_13",
    "Précision si autre"="Q6_13_Pr",
    
  )
```

## Renommage des modalités 

```{r}
data <- data %>%
  mutate(Sexe = recode(Sexe,
                       `1` = "H",
                       `2` = "F",
                       `3` = "Autre"))

data <- data %>%
  mutate(`Tranche d'âge` = recode(`Tranche d'âge`,
                                  `1` = "20-24 ans",
                                  `2` = "25-34 ans",
                                  `3` = "35-44 ans",
                                  `4` = "45-54 ans",
                                  `5` = "55-64 ans",
                                  `6` = "65 ans et plus"))

data <- data %>%
  mutate(CSP = recode(CSP,
                      `1` = "Agriculteur",
                      `2` = "Artisan",
                      `3` = "Commerçant",
                      `4` = "Chef d’entreprise",
                      `5` = "Profession libérale",
                      `6` = "Cadre ou profession intellectuelle supérieure",
                      `7` = "Profession intermédiaire",
                      `8` = "Employé",
                      `9` = "Ouvrier",
                      `10` = "Retraité",
                      `11` = "Demandeur d’emploi",
                      `12` = "Homme ou Femme au foyer",
                      `13` = "Etudiant, lycéen",
                      `14` = "Autre"))

library(dplyr)

data <- data %>%
  mutate(`Groupe de CSP` = case_when(
    CSP %in% c("Agriculteur", "Artisan", "Commerçant", "Chef d’entreprise") ~ 
      "Agriculteur, Artisan, Commerçant, Chef d’entreprise",
    
    CSP %in% c("Profession libérale", "Cadre ou profession intellectuelle supérieure") ~ 
      "Profession libérale, Cadre ou profession intellectuelle supérieure",
    
    CSP == "Profession intermédiaire" ~ 
      "Profession intermédiaire",
    
    CSP %in% c("Employé", "Ouvrier") ~ 
      "Employé, Ouvrier",
    
    CSP == "Retraité" ~ 
      "Retraité",
    
    CSP %in% c("Demandeur d’emploi", "Homme ou Femme au foyer", "Etudiant, lycéen", "Autre") ~ 
      "Demandeur d’emploi, Homme ou Femme au foyer, Etudiant, lycéen, Autre"
  ))


data <- data %>%
  mutate(`Responsable achats alimentaire` = recode(`Responsable achats alimentaire`,
    `1` = "Oui, intégralement",
    `2` = "Oui, partiellement",
    `3` = "Non, je ne m'occupe pas des achats alimentaires de mon foyer"
  ))


data <- data %>%
  mutate(across(
    c(
      `Hypermarché, Supermarché`,
      `Hard discount`,
      `Epiceries indépendantes, de quartier, épiceries fines`,
      `Magains de surgelés`,
      `Magasins spécialisés Bio`,
      `Marché`,
      `Directement aux agriculteurs`,
      `Paniers en ligne réalisés par un intermédiaire`,
      `Artisans et commerçants spécialisés`,
      `Epicerie participative, associative, supermarché coopératif`,
      `Magasin alimentaire spécialisé dans le vrac ou les produits locaux`,
      `Magasin d’aide alimentaire`,
      `Autre`
    ),
    ~ recode(.,
      `1` = "Plusieurs fois par semaine",
      `2` = "1 fois par semaine",
      `3` = "2 à 3 fois par mois",
      `4` = "1 fois par mois",
      `5` = "Moins d’une fois par mois",
      `6` = "Seulement pour des événements particuliers",
      `7` = "Jamais"
    )
  ))


```















