---
title: "Fonction_comparaison_prix_kg_Shiny_vs_Manon"
format: html
editor: visual
---

```{r}
# Comparaison des 2 fichiers 
data_comparaison <- inner_join(data_ok, data_calculable, by = "idOrder")

# Vérification aucune valeur manquante dans idOrder 
sum(is.na(data_comparaison$idOrder))

# Filtrons les lignes où le prix de la table de Manon et la notre est correct
data_comparaison <- data_comparaison |> filter(prixKilo.x == prixKilo.y)
```

```{r}
# Fonction : Comparaison aux résultats Manon 

comparaison_prix_kg <- function(data_test,data_Manon){

  # Créons une nouvelle variable pour calculer le prix au kg 
  data_test <- data_sortie[[1]] 
  data_test <- data_test |> mutate(prixKilo = orderProductPrice / poidsenkg)
  
  # Si c'est un facteur, on le transforme en caractère d'abord
  data_Manon$prixKilo <- as.character(data_Manon$prixKilo)
  
  # Remplacement de la virgule par un point
  data_Manon$prixKilo <- gsub(",", ".", data_Manon$prixKilo)
  
  # Conversion en numérique
  data_Manon$prixKilo <- as.numeric(data_Manon$prixKilo)
  
  # Comparaison des 2 fichiers 
  data_comparaison <- inner_join(data_test, data_Manon, by = "idOrder")

  # Filtrons les lignes où le prix de la table de Manon et la notre est correct
  data_comparaison <- data_comparaison |> filter(prixKilo.x == prixKilo.y)
  
  return(data_comparaison)
    
}
```

```{r}
# Test de la fonction comparaison aux résultats Manon
data_comparaison <- comparaison_prix_kg(data_sortie,data_ok_courgettes)
```

