- Abricot
- Banane
- Cerise
- Clémentine
- Fraise
- Kiwi
- Nectarine
- Noix
- Pêche
- Poire
- Pomme de terre
- Jus de Pomme
- Pomme
- Prune
- Raisin
- Asperge
- Aubergine
- Carotte
- Céleri branche
- Chou fleur
- Concombre
- Courgette
- Endive
- Haricot vert
- Laitue
- Melon
- Oignon
- Poireau
- Poivron
- Potiron
- Tomate
- Lait
- Œuf
- Boeuf
- Porc
- Poulet
- Lentille
- Laitue pomme
- Pruneaux
