# Packages ----------------------------------------------------------------
library(writexl)
library(stringr)
library(stringi)
library(tidyverse)
library(data.table)

# Nettoyage de chaine de caractères ---------------------------------------

nettoyer <- function(chaines){
  chaines <- str_to_lower(chaines) # Mise en minuscules
  chaines <- stri_trans_general(chaines, "Latin-ASCII") # Supprimer les accents
  chaines <- str_replace_all(chaines, "[^a-z ]", "") # Supprimer les tirets
  chaines <- trimws(chaines) 
  return(chaines)
}

# Liste de produits éligibles ---------------------------------------------

liste_produits <- nettoyer(yaml::read_yaml("data/products.yaml"))
ordre <- order(nchar(gsub(" ", "", liste_produits)), decreasing = TRUE)
liste_produits <- liste_produits[ordre] 

# La liste des produits transformés ---------------------------------------
produit_transforme <- yaml::read_yaml("data/produits_transforme.yaml")
produit_transforme <- unique(produit_transforme)

# Generer des expressions régulières --------------------------------------

creer_regex <- function(mots, suffixe = "(e?s)?", collapse = ".*") {
  sapply(mots, function(terme) {
    tokens <- str_split(terme, " ")[[1]] 
    regex_tokens <- paste0(tokens, suffixe)
    paste0(regex_tokens, collapse = collapse)
  })
}

# Extraires toutes declinaisons des noms de produits ----------------------

trouver_declinaisons_nom_produit <- function(dataset, col_produit, ls_produit, regex) {
  # Extraction des noms uniques de produits
  noms_des_produits <- nettoyer(dataset[[col_produit]])
  noms_des_produits_uniques <- unique(noms_des_produits)
  # Extraction des déclinaisons par produit
  liste_declinaisons <- sapply(seq_along(regex), function(i) {
    extractions <- str_extract(noms_des_produits_uniques, regex[i])
    extractions[extractions == ""] <- NA
    extractions <- unique(extractions[!is.na(extractions)])
    extractions
  }, simplify = FALSE)
  
  names(liste_declinaisons) <- ls_produit
  return(liste_declinaisons)
}

# Dataframe par produit unique ---------------------------------------------

creer_dataframes_par_declinaison <- function(donnees, col_prod, declinaisons_produits) {
  # 1. Définition des produits à conserver et nettoyage des données
  produits_a_conserver <- names(declinaisons_produits)
  noms_produits_bruts <- nettoyer(donnees[[col_prod]])
  produits_uniques_dataset <- unique(noms_produits_bruts)
  # 2. Création de listes avec des dataframes pour chaque produit conservé
  dataframes_par_declinaison <- lapply(seq_along(declinaisons_produits), function(i) {
    produit_courant <- names(declinaisons_produits)[i]  # Nom du produit actuellement traité
    produits_non_courants <- setdiff(produits_a_conserver, produit_courant)
    declinaisons_non_courants <- unlist(declinaisons_produits[produits_non_courants])
    # Identifier les noms de produits correspondant à chaque déclinaison
    noms_produits_match_declinaison <- sapply(declinaisons_produits[[i]], function(declinaison) {
      # Chercher les produits qui correspondent à la déclinaison courante
      correspondance <- grepl(declinaison, produits_uniques_dataset, fixed = TRUE)
      matches <- produits_uniques_dataset[correspondance]
      produits_uniques_dataset <<- setdiff(produits_uniques_dataset, matches)
      matches_copy <- gsub(declinaison, " ", matches)
      
      s <- sapply(declinaisons_non_courants, function(x){
        recherche <- grepl(x, matches_copy, fixed = TRUE)
        matches[recherche]
      })
      setdiff(matches, unlist(s))
    })
    
    donnees[noms_produits_bruts %in% unique(unlist(noms_produits_match_declinaison)),]
  })
  names(dataframes_par_declinaison) <- produits_a_conserver
  return(dataframes_par_declinaison)
}
